import "dotenv/config";
import { prisma } from "../lib/prisma.js";
import { FOUNDER_DEMO_IDS, founderDemoBlueprint, founderDemoDocuments, founderDemoSimulation } from "./founder-demo-data.js";

const slug = "simforge-customer-support-academy-demo";

async function seed() {
  const ownerEmail = process.env.DEMO_OWNER_EMAIL?.trim().toLowerCase();
  if (!ownerEmail) throw new Error("DEMO_OWNER_EMAIL is required. Sign in once with the founder demo user, then rerun the seed.");
  const owner = await prisma.profile.findFirst({ where: { email: { equals: ownerEmail, mode: "insensitive" } } });
  if (!owner) throw new Error("No matching profile exists. Sign in to SimForge once with the demo user before seeding.");
  const existingDemo = await prisma.organization.findUnique({ where: { slug } });
  const memberships = await prisma.membership.findMany({ where: { userId: owner.id }, select: { organizationId: true, organization: { select: { slug: true } } } });
  if (memberships.some((membership) => membership.organization.slug !== slug)) throw new Error("The demo owner already belongs to another organization. Use a dedicated Supabase Auth user for founder acceptance testing.");

  const result = await prisma.$transaction(async (transaction) => {
    const organization = await transaction.organization.upsert({
      where: { slug },
      create: { id: existingDemo?.id ?? FOUNDER_DEMO_IDS.organization, name: "SimForge Customer Support Academy", slug, industry: "Customer Support / SaaS", companySize: "51–200", country: "India", timezone: "Asia/Kolkata", createdBy: owner.id },
      update: { name: "SimForge Customer Support Academy", industry: "Customer Support / SaaS", companySize: "51–200", country: "India", timezone: "Asia/Kolkata" },
    });
    await transaction.membership.upsert({ where: { organizationId_userId: { organizationId: organization.id, userId: owner.id } }, create: { organizationId: organization.id, userId: owner.id, role: "Owner" }, update: { role: "Owner" } });
    await transaction.organizationBlueprint.upsert({ where: { organizationId: organization.id }, create: { organizationId: organization.id, ...founderDemoBlueprint, status: "APPROVED" }, update: { ...founderDemoBlueprint, status: "APPROVED" } });
    const knowledgeBase = await transaction.knowledgeBase.upsert({ where: { organizationId_name: { organizationId: organization.id, name: "Customer Support Operations" } }, create: { id: FOUNDER_DEMO_IDS.knowledgeBase, organizationId: organization.id, name: "Customer Support Operations", description: "Governed support policies, SOPs, and response guidance for founder acceptance testing.", department: "Customer Support", createdBy: owner.id }, update: { description: "Governed support policies, SOPs, and response guidance for founder acceptance testing.", department: "Customer Support", status: "Active" } });

    for (const document of founderDemoDocuments) {
      const storagePath = `${organization.id}/${knowledgeBase.id}/founder-demo/${document.id}.docx`;
      await transaction.document.upsert({ where: { id: document.id }, create: { id: document.id, knowledgeBaseId: knowledgeBase.id, fileName: document.fileName, fileType: "DOCX", mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", sizeBytes: document.content.length, storagePath, uploadedBy: owner.id, notes: "Founder acceptance demo metadata; processed text and intelligence are seeded for real platform use." }, update: { knowledgeBaseId: knowledgeBase.id, fileName: document.fileName, sizeBytes: document.content.length, storagePath, uploadedBy: owner.id, status: "Ready", notes: "Founder acceptance demo metadata; processed text and intelligence are seeded for real platform use." } });
      await transaction.documentVersion.upsert({ where: { documentId_version: { documentId: document.id, version: 1 } }, create: { documentId: document.id, version: 1, fileName: document.fileName, fileType: "DOCX", mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", sizeBytes: document.content.length, storagePath, uploadedBy: owner.id, notes: "Seeded demo version" }, update: { fileName: document.fileName, sizeBytes: document.content.length, storagePath, uploadedBy: owner.id, notes: "Seeded demo version" } });
      const source = await transaction.knowledgeSource.upsert({ where: { documentId: document.id }, create: { id: document.sourceId, organizationId: organization.id, documentId: document.id, sourceType: "DOCX", title: document.title, mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", sizeBytes: document.content.length, status: "Completed", progress: 100, extractedText: document.content, pageCount: 1, wordCount: document.content.split(/\s+/u).length, characterCount: document.content.length, estimatedTokens: Math.ceil(document.content.length / 4), language: "eng", processingDurationMs: 1, processedAt: new Date() }, update: { organizationId: organization.id, title: document.title, status: "Completed", progress: 100, extractedText: document.content, pageCount: 1, wordCount: document.content.split(/\s+/u).length, characterCount: document.content.length, estimatedTokens: Math.ceil(document.content.length / 4), language: "eng", processingDurationMs: 1, processedAt: new Date(), failureReason: null } });
      await transaction.knowledgeChunk.upsert({ where: { sourceId_chunkNumber: { sourceId: source.id, chunkNumber: 1 } }, create: { sourceId: source.id, documentId: document.id, chunkNumber: 1, text: document.content, characterCount: document.content.length, estimatedTokens: Math.ceil(document.content.length / 4), metadata: { seededDemo: true, fileName: document.fileName } }, update: { documentId: document.id, text: document.content, characterCount: document.content.length, estimatedTokens: Math.ceil(document.content.length / 4), metadata: { seededDemo: true, fileName: document.fileName } } });
      for (const [index, section] of document.sections.entries()) await transaction.knowledgeIntelligenceSection.upsert({ where: { sourceId_sectionNumber: { sourceId: source.id, sectionNumber: index + 1 } }, create: { id: section.id, sourceId: source.id, sectionNumber: index + 1, title: section.title, summary: section.summary, sectionType: section.sectionType, confidence: section.confidence, keywords: [...section.keywords], importance: section.importance, capabilities: [...section.capabilities], isAiSuggestion: true, analysisVersion: "founder-demo-v1" }, update: { title: section.title, summary: section.summary, sectionType: section.sectionType, confidence: section.confidence, keywords: [...section.keywords], importance: section.importance, capabilities: [...section.capabilities], isAiSuggestion: true, analysisVersion: "founder-demo-v1" } });
    }

    const persona = await transaction.simulationPersona.upsert({ where: { organizationId_name: { organizationId: organization.id, name: founderDemoSimulation.persona.name } }, create: { id: FOUNDER_DEMO_IDS.persona, organizationId: organization.id, createdBy: owner.id, ...founderDemoSimulation.persona }, update: founderDemoSimulation.persona });
    const criteria = [];
    for (const name of founderDemoSimulation.evaluationCriteria) criteria.push(await transaction.simulationEvaluationCriterion.upsert({ where: { organizationId_name: { organizationId: organization.id, name } }, create: { organizationId: organization.id, name, description: `Evaluate ${name.toLowerCase()} using observable session evidence.`, isDefault: true, createdBy: owner.id }, update: { description: `Evaluate ${name.toLowerCase()} using observable session evidence.`, isDefault: true } }));
    await transaction.simulation.upsert({ where: { id: FOUNDER_DEMO_IDS.simulation }, create: { id: FOUNDER_DEMO_IDS.simulation, organizationId: organization.id, createdBy: owner.id, personaId: persona.id, title: founderDemoSimulation.title, description: founderDemoSimulation.description, industry: founderDemoSimulation.industry, department: founderDemoSimulation.department, jobRole: founderDemoSimulation.jobRole, category: founderDemoSimulation.category, difficulty: founderDemoSimulation.difficulty, status: founderDemoSimulation.status, estimatedMinutes: founderDemoSimulation.estimatedMinutes, scenarioSetup: founderDemoSimulation.scenarioSetup, successCriteria: founderDemoSimulation.successCriteria }, update: { personaId: persona.id, title: founderDemoSimulation.title, description: founderDemoSimulation.description, industry: founderDemoSimulation.industry, department: founderDemoSimulation.department, jobRole: founderDemoSimulation.jobRole, category: founderDemoSimulation.category, difficulty: founderDemoSimulation.difficulty, status: founderDemoSimulation.status, estimatedMinutes: founderDemoSimulation.estimatedMinutes, scenarioSetup: founderDemoSimulation.scenarioSetup, successCriteria: founderDemoSimulation.successCriteria } });
    await transaction.simulationObjective.deleteMany({ where: { simulationId: FOUNDER_DEMO_IDS.simulation } });
    await transaction.simulationObjective.createMany({ data: founderDemoSimulation.objectives.map((title, sortOrder) => ({ simulationId: FOUNDER_DEMO_IDS.simulation, title, sortOrder })) });
    await transaction.simulationCriterionLink.deleteMany({ where: { simulationId: FOUNDER_DEMO_IDS.simulation } });
    await transaction.simulationCriterionLink.createMany({ data: criteria.map((criterion) => ({ simulationId: FOUNDER_DEMO_IDS.simulation, criterionId: criterion.id })) });
    await transaction.simulationKnowledgeBase.upsert({ where: { simulationId_knowledgeBaseId: { simulationId: FOUNDER_DEMO_IDS.simulation, knowledgeBaseId: knowledgeBase.id } }, create: { simulationId: FOUNDER_DEMO_IDS.simulation, knowledgeBaseId: knowledgeBase.id }, update: {} });
    await transaction.simulationVersion.upsert({ where: { simulationId_version: { simulationId: FOUNDER_DEMO_IDS.simulation, version: 1 } }, create: { simulationId: FOUNDER_DEMO_IDS.simulation, version: 1, snapshot: { seededDemo: true, title: founderDemoSimulation.title } }, update: { snapshot: { seededDemo: true, title: founderDemoSimulation.title } } });
    return { organization: organization.name, documents: founderDemoDocuments.length, simulation: founderDemoSimulation.title };
  });
  console.log(`Founder demo ready: ${result.organization}; ${result.documents} knowledge documents; simulation “${result.simulation}”.`);
}

seed().catch((error: unknown) => { console.error(error instanceof Error ? error.message : "Founder demo seed failed"); process.exitCode = 1; }).finally(() => prisma.$disconnect());
