import { ArrowRight, BookOpenCheck, CheckCircle2, CircleSlash2, Clock3, Compass, Lightbulb, MessageSquareQuote, Sparkles } from "lucide-react";
import { experienceBestPractices, experienceFaq, experienceWorkflow, foundations, founderTalkingPoints, futureFoundations, notAnLms, demoWalkthrough } from "@/lib/experience-center-content";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { PageHeading } from "@/components/layout/page-heading";

export function ExperienceCenter() {
  return <div className="mx-auto max-w-7xl space-y-12 pb-8">
    <section className="overflow-hidden rounded-2xl border bg-card p-6 shadow-sm sm:p-8 lg:p-10">
      <Badge variant="outline">Experience Center</Badge>
      <div className="mt-5 grid gap-8 lg:grid-cols-[1.3fr_0.7fr] lg:items-center">
        <div><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">Welcome to SimForge</h1><p className="mt-4 max-w-3xl text-base leading-7 text-muted-foreground sm:text-lg">SimForge helps organizations transform company knowledge into measurable workforce capability.</p><p className="mt-4 max-w-3xl text-sm leading-6 text-muted-foreground">Use this guide to explain the product, prepare a focused demonstration, and understand how each foundation contributes to the complete experience.</p></div>
        <div className="rounded-xl border bg-muted/35 p-5"><Compass className="size-6 text-primary" /><p className="mt-4 text-sm font-semibold">The simplest explanation</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Knowledge becomes practice. Practice becomes evidence. Evidence guides improvement.</p></div>
      </div>
    </section>

    <section><PageHeading eyebrow="Product workflow" title="How SimForge works" description="Six connected steps turn organizational knowledge into measurable improvement." /><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{experienceWorkflow.map((item, index) => <div key={item.title} className="relative rounded-xl border bg-card p-4"><span className="grid size-7 place-items-center rounded-full bg-primary/10 text-xs font-semibold text-primary">{index + 1}</span><h3 className="mt-4 text-sm font-semibold">{item.title}</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">{item.description}</p>{index < experienceWorkflow.length - 1 && <ArrowRight className="absolute -right-2.5 top-5 z-10 hidden size-5 rounded-full bg-background text-muted-foreground xl:block" />}</div>)}</div></section>

    <section><PageHeading eyebrow="Positioning" title="What SimForge is not" description="Clear boundaries make the product easier to understand and position." /><div className="mt-6 grid gap-4 md:grid-cols-2">{notAnLms.map((item) => <Card key={item.title}><CardHeader><CardTitle className="flex items-center gap-2 text-base"><CircleSlash2 className="size-4 text-muted-foreground" />{item.title}</CardTitle></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">{item.description}</p></CardContent></Card>)}</div></section>

    <section><PageHeading eyebrow="Platform" title="Core foundations" description="Each foundation has one clear job in the SimForge system." /><div className="mt-6 grid gap-4 md:grid-cols-2">{foundations.map((item, index) => <Card key={item.title}><CardHeader><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-primary/10 text-sm font-semibold text-primary">{index + 1}</span><CardTitle className="text-base">{item.title}</CardTitle></div></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">{item.description}</p></CardContent></Card>)}</div><Card className="mt-4 border-dashed"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Sparkles className="size-4 text-primary" />Future foundations</CardTitle><CardDescription>Planned extensions—not part of today’s core workflow.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-2">{futureFoundations.map((item) => <Badge key={item} variant="secondary">{item}</Badge>)}</CardContent></Card></section>

    <section><PageHeading eyebrow="15-minute guide" title="Demo walkthrough" description="A concise narrative for customer conversations, internal reviews, and pilot discussions." /><div className="mt-6 space-y-3">{demoWalkthrough.map((item) => <Card key={item.time}><CardContent className="grid gap-3 p-5 sm:grid-cols-[9rem_1fr] sm:items-start"><div className="flex items-center gap-2 text-sm font-semibold text-primary"><Clock3 className="size-4" />{item.time}</div><div><h3 className="text-sm font-semibold">{item.title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{item.description}</p></div></CardContent></Card>)}</div></section>

    <section className="grid gap-6 lg:grid-cols-2">
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><MessageSquareQuote className="size-5 text-primary" />How to explain SimForge in simple words</CardTitle><CardDescription>Founder explanation mode: five short points that tell the complete story.</CardDescription></CardHeader><CardContent><ol className="space-y-3">{founderTalkingPoints.map((point, index) => <li key={point} className="flex items-center gap-3 rounded-lg border p-3 text-sm"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-primary/10 text-xs font-semibold text-primary">{index + 1}</span>{point}</li>)}</ol></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><Lightbulb className="size-5 text-primary" />Best practices</CardTitle><CardDescription>Keep the first implementation focused, governed, and useful.</CardDescription></CardHeader><CardContent className="space-y-4">{experienceBestPractices.map((item) => <div key={item.title} className="flex gap-3"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-emerald-600 dark:text-emerald-400" /><div><h3 className="text-sm font-medium">{item.title}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{item.description}</p></div></div>)}</CardContent></Card>
    </section>

    <section><PageHeading eyebrow="Common questions" title="FAQ" description="Straight answers for customers, admins, trainers, and internal stakeholders." /><div className="mt-6 space-y-3">{experienceFaq.map((item) => <details key={item.question} className="group rounded-xl border bg-card"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-5 text-sm font-semibold"><span>{item.question}</span><span className="text-lg font-normal text-muted-foreground transition-transform group-open:rotate-45">+</span></summary><div className="border-t px-5 py-4"><p className="text-sm leading-6 text-muted-foreground">{item.answer}</p></div></details>)}</div></section>

    <div className="rounded-xl border border-dashed p-5 text-center"><BookOpenCheck className="mx-auto size-5 text-primary" /><p className="mt-2 text-sm font-medium">Use this page as the shared product narrative.</p><p className="mt-1 text-xs text-muted-foreground">Keep customer demos focused on one business problem, one realistic scenario, and one measurable capability outcome.</p></div>
  </div>;
}
