-- Complete API-owned table hardening.
-- Membership intentionally keeps its narrow authenticated SELECT access because
-- Supabase Storage policies use the caller's own membership row for authorization.
-- Every other Prisma business table is API-only and rejects direct anon/authenticated access.

ALTER TABLE public."Profile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Organization" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."OrganizationBlueprint" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."KnowledgeBase" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Simulation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."SimulationPersona" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."SimulationObjective" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."SimulationEvaluationCriterion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."SimulationCriterionLink" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."SimulationKnowledgeBase" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."SimulationVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."SimulationSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."PracticeAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Assessment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."AssessmentAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."AssessmentAttempt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."DevelopmentPath" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."DevelopmentPathStep" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."DevelopmentPathAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."DevelopmentPathStepProgress" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."SimulationCoachingInsight" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."LearnerCapabilityProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."LearnerCapability" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."CapabilityAssessmentHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."SimulationMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."SimulationEvaluation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."CapabilityScore" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Document" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."LearningFactoryDraft" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."KnowledgeSource" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."KnowledgeIntelligenceSection" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ProcessingJob" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."KnowledgeChunk" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."KnowledgeChunkEmbedding" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ProcessingLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."DocumentVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Activity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Membership" ENABLE ROW LEVEL SECURITY;

REVOKE ALL PRIVILEGES ON TABLE public."Profile" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."Profile" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."Organization" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."Organization" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."OrganizationBlueprint" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."OrganizationBlueprint" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."KnowledgeBase" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."KnowledgeBase" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."Simulation" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."Simulation" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."SimulationPersona" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."SimulationPersona" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."SimulationObjective" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."SimulationObjective" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."SimulationEvaluationCriterion" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."SimulationEvaluationCriterion" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."SimulationCriterionLink" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."SimulationCriterionLink" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."SimulationKnowledgeBase" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."SimulationKnowledgeBase" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."SimulationVersion" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."SimulationVersion" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."SimulationSession" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."SimulationSession" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."PracticeAssignment" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."PracticeAssignment" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."Assessment" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."Assessment" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."AssessmentAssignment" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."AssessmentAssignment" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."AssessmentAttempt" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."AssessmentAttempt" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."DevelopmentPath" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."DevelopmentPath" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."DevelopmentPathStep" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."DevelopmentPathStep" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."DevelopmentPathAssignment" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."DevelopmentPathAssignment" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."DevelopmentPathStepProgress" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."DevelopmentPathStepProgress" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."SimulationCoachingInsight" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."SimulationCoachingInsight" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."LearnerCapabilityProfile" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."LearnerCapabilityProfile" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."LearnerCapability" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."LearnerCapability" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."CapabilityAssessmentHistory" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."CapabilityAssessmentHistory" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."SimulationMessage" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."SimulationMessage" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."SimulationEvaluation" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."SimulationEvaluation" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."CapabilityScore" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."CapabilityScore" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."Document" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."Document" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."LearningFactoryDraft" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."LearningFactoryDraft" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."KnowledgeSource" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."KnowledgeSource" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."KnowledgeIntelligenceSection" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."KnowledgeIntelligenceSection" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."ProcessingJob" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."ProcessingJob" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."KnowledgeChunk" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."KnowledgeChunk" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."KnowledgeChunkEmbedding" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."KnowledgeChunkEmbedding" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."ProcessingLog" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."ProcessingLog" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."DocumentVersion" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."DocumentVersion" FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."Activity" FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public."Activity" FROM authenticated;
